import "./globals.css";
import { Inter } from "next/font/google";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
} from "@clerk/nextjs";
import { UserButton } from "@clerk/nextjs";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const currentMonth = () => {
  const currentDate = new Date();
  return `${currentDate.getMonth() + 1}/${currentDate.getFullYear()}`;
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const statsLink = `/stats/${currentMonth()}`;

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} dark`}>
          <div className="flex justify-between p-2">
            <Link href="/">Home</Link>
            <Link href={statsLink}>Stats</Link>
            <SignedIn>
              <UserButton afterSignOutUrl="/" />
            </SignedIn>
            <SignedOut>
              <SignInButton />
            </SignedOut>
          </div>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
